# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "term", # <tidy.DESeqDataSet>
  ".", # <tidy.DESeqDataSet>
  "count", # <tidy.DESeqDataSet>
  "gene", # <tidy.DESeqDataSet>
  "log2Count", # <tidy.DESeqTransform>
  "gene", # <tidy.DESeqTransform>
  "value", # <tidy.ExpressionSet>
  "gene", # <tidy.ExpressionSet>
  "sample.id", # <tidy.MSnSet>
  "value", # <tidy.MSnSet>
  "protein", # <tidy.MSnSet>
  "value", # <tidy.RangedSummarizedExperiment>
  "gene", # <tidy.RangedSummarizedExperiment>
  "value", # <tidy.deSet>
  "gene", # <tidy.deSet>
  "term", # <tidy.MArrayLM>
  "estimate", # <tidy.MArrayLM>
  "gene", # <tidy.MArrayLM>
  "smoothed", # <tidy.qvalue>
  "pi0", # <tidy.qvalue>
  "lambda", # <tidy.qvalue>
  NULL
))
